image: maven:3-openjdk-8

stages:
- deploy
- test

default:
  before_script:
    - 'which ssh-agent || ( apk add --update openssh-client )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

deploy:
  stage: deploy
  script:
    - ./gradlew build
    - 'curl -s --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file lib/build/libs/PIDMRHDLProxy-0.0.1-SNAPSHOT.jar "https://gitlab-ce.gwdg.de/api/v4/projects/24967/packages/maven/eu/faircore4eosc/lib/0.0.1-SNAPSHOT/pidmrhdlproxy-0.1.jar"'
    - scp lib/build/libs/PIDMRHDLProxy-0.0.1-SNAPSHOT.jar lib/build/libs/influxdb-2.24.jar $SSH_LOGIN:/home/cloud
    - ssh $SSH_LOGIN "$PIDMR_PROXY_RESTART_SCRIPT"

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
